controller_list:
  - name: kuka_arm/fake_arm_controller
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - left_gripper_finger_joint
      - right_gripper_finger_joint
  - name: kuka_arm/fake_gripper_group_controller
    default: true
    joints:
      - left_gripper_finger_joint
      - right_gripper_finger_joint