sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudEsdfUpdater
    point_cloud_topic: /move_group_sensor_input
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    filtered_cloud_topic: filtered_cloud